# Generated by Django 5.2 on 2026-01-02 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('complete', 'Complete')], db_index=True, default='pending', max_length=15),
        ),
    ]
